### ISSUE TITLE
Flash of 'light mode' before 'dark mode' takes effect on reload

### ISSUE THREAD

**Issue by benallfree** [benallfree/pockethost#32]
Anything we can do about this @brewhousedigital ?

**Comment by brewhousedigital** [comment]
Checking into this to see if we can get it sent with the initial payload

**Comment by benallfree** [comment]
Yeah like an SSR cookie thing maybe?

**Comment by brewhousedigital** [comment]
Seems like the flow should act something like this:

1. First time user lands on the site and gets default theme set to `light`
2. Toggling the theme saves a `theme` cookie with the theme value
3. When a reload happens, the UI uses `+layout.server.js` to read the cookies and check for theme value
4. It then updates the HTML being sent to the client

That last step I haven't quite figured out, especially since the latest SvelteKit update to RC. They haven't fully outlined the docs for it, and a lot of tutorials are using svelte functions that aren't available or have changed in some manner.

Feel free to take a stab at it if you'd like. Otherwise, I can set the theme to pull from the Operating System setting, and it won't flash anymore, but then the toggle would need to be removed. Let me know what you think.

**Comment by benallfree** [comment]
My read is that https://kit.svelte.dev/docs/load#cookies-and-headers will help us. Using that, we can use `load` to do an SSR cookie inspection and return the dark mode setting.

**Comment by brewhousedigital** [comment]
I think the way I implemented dark mode will need to be changed. I was using a `data attribute` on the `<html>` tag which i'm not sure can be modified using SSR. May need to target the main Svelte `<div>` instead. I'll play around with it some more.

**Comment by benallfree** [comment]
I think it can be. Svelte has a `handle` hook that is called for reach request https://kit.svelte.dev/docs/types#sveltejs-kit:

```ts
// hooks.server.ts

import type { Handle } from '@sveltejs/kit'

const handle: Handle = async ({ event, resolve }) => {
  const response = await resolve(event)
  response.body?.pipeThrough(...) // 
  return response
}

export { handle }
```

`response.body` is a `ReadableStream` which can be piped through a `TransformStream` to replace the the dark mode value with whatever is in the cookie
https://developer.mozilla.org/en-US/docs/Web/API/TransformStream

There is also Vite middleware which could do the same.

Or we could hook into `%sveltekit.head%` and inject some JS in the `<head>` section that reads the cookie (defaulting to `light`) and adds the attribute to the `<html>` tag. Because it would run in `<head>` before anything was rendered, that would work fine.

Now that I've said all that, the pure JS solution seems like it would be the best and easiest. It would avoid having to do server-side stream transformations on every request.
